apiVersion: opsmanager.crossplane.io/v1alpha1
kind: Project
metadata:
  name: test-backup
spec:
  providerConfigRef:
    name: default
  forProvider:
    name: "test-backup"
    orgId: "6a09b573a4d0a92fff4a29fb"
