//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// ---- OpsManagerProject ----

func (in *OpsManagerProject) DeepCopyInto(out *OpsManagerProject) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *OpsManagerProject) DeepCopy() *OpsManagerProject {
	if in == nil {
		return nil
	}
	out := new(OpsManagerProject)
	in.DeepCopyInto(out)
	return out
}

func (in *OpsManagerProject) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *OpsManagerProjectList) DeepCopyInto(out *OpsManagerProjectList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OpsManagerProject, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *OpsManagerProjectList) DeepCopy() *OpsManagerProjectList {
	if in == nil {
		return nil
	}
	out := new(OpsManagerProjectList)
	in.DeepCopyInto(out)
	return out
}

func (in *OpsManagerProjectList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *OpsManagerProjectSpec) DeepCopyInto(out *OpsManagerProjectSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

func (in *OpsManagerProjectSpec) DeepCopy() *OpsManagerProjectSpec {
	if in == nil {
		return nil
	}
	out := new(OpsManagerProjectSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *OpsManagerProjectStatus) DeepCopyInto(out *OpsManagerProjectStatus) {
	*out = *in
	in.ConditionedStatus.DeepCopyInto(&out.ConditionedStatus)
	out.AtProvider = in.AtProvider
}

func (in *OpsManagerProjectStatus) DeepCopy() *OpsManagerProjectStatus {
	if in == nil {
		return nil
	}
	out := new(OpsManagerProjectStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *OpsManagerProjectParameters) DeepCopyInto(out *OpsManagerProjectParameters) {
	*out = *in
	if in.LDAPGroupMappings != nil {
		in, out := &in.LDAPGroupMappings, &out.LDAPGroupMappings
		*out = make([]LDAPGroupMapping, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *OpsManagerProjectParameters) DeepCopy() *OpsManagerProjectParameters {
	if in == nil {
		return nil
	}
	out := new(OpsManagerProjectParameters)
	in.DeepCopyInto(out)
	return out
}

func (in *LDAPGroupMapping) DeepCopyInto(out *LDAPGroupMapping) {
	*out = *in
	if in.LDAPGroups != nil {
		in, out := &in.LDAPGroups, &out.LDAPGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

func (in *LDAPGroupMapping) DeepCopy() *LDAPGroupMapping {
	if in == nil {
		return nil
	}
	out := new(LDAPGroupMapping)
	in.DeepCopyInto(out)
	return out
}

func (in *OpsManagerProjectObservation) DeepCopyInto(out *OpsManagerProjectObservation) {
	*out = *in
}

func (in *OpsManagerProjectObservation) DeepCopy() *OpsManagerProjectObservation {
	if in == nil {
		return nil
	}
	out := new(OpsManagerProjectObservation)
	in.DeepCopyInto(out)
	return out
}

// ---- S3Blockstore ----

func (in *S3Blockstore) DeepCopyInto(out *S3Blockstore) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *S3Blockstore) DeepCopy() *S3Blockstore {
	if in == nil {
		return nil
	}
	out := new(S3Blockstore)
	in.DeepCopyInto(out)
	return out
}

func (in *S3Blockstore) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *S3BlockstoreList) DeepCopyInto(out *S3BlockstoreList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]S3Blockstore, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *S3BlockstoreList) DeepCopy() *S3BlockstoreList {
	if in == nil {
		return nil
	}
	out := new(S3BlockstoreList)
	in.DeepCopyInto(out)
	return out
}

func (in *S3BlockstoreList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *S3BlockstoreSpec) DeepCopyInto(out *S3BlockstoreSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

func (in *S3BlockstoreSpec) DeepCopy() *S3BlockstoreSpec {
	if in == nil {
		return nil
	}
	out := new(S3BlockstoreSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *S3BlockstoreStatus) DeepCopyInto(out *S3BlockstoreStatus) {
	*out = *in
	in.ConditionedStatus.DeepCopyInto(&out.ConditionedStatus)
	out.AtProvider = in.AtProvider
}

func (in *S3BlockstoreStatus) DeepCopy() *S3BlockstoreStatus {
	if in == nil {
		return nil
	}
	out := new(S3BlockstoreStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *S3BlockstoreParameters) DeepCopyInto(out *S3BlockstoreParameters) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AssignmentEnabled != nil {
		in, out := &in.AssignmentEnabled, &out.AssignmentEnabled
		*out = new(bool)
		**out = **in
	}
	if in.SSL != nil {
		in, out := &in.SSL, &out.SSL
		*out = new(bool)
		**out = **in
	}
	if in.EncryptedCredentials != nil {
		in, out := &in.EncryptedCredentials, &out.EncryptedCredentials
		*out = new(bool)
		**out = **in
	}
	if in.LoadFactor != nil {
		in, out := &in.LoadFactor, &out.LoadFactor
		*out = new(int64)
		**out = **in
	}
	if in.MaxCapacityGB != nil {
		in, out := &in.MaxCapacityGB, &out.MaxCapacityGB
		*out = new(int64)
		**out = **in
	}
	if in.Provisioned != nil {
		in, out := &in.Provisioned, &out.Provisioned
		*out = new(bool)
		**out = **in
	}
	if in.PathStyleAccessEnabled != nil {
		in, out := &in.PathStyleAccessEnabled, &out.PathStyleAccessEnabled
		*out = new(bool)
		**out = **in
	}
	if in.SSEEnabled != nil {
		in, out := &in.SSEEnabled, &out.SSEEnabled
		*out = new(bool)
		**out = **in
	}
	if in.AcceptedTos != nil {
		in, out := &in.AcceptedTos, &out.AcceptedTos
		*out = new(bool)
		**out = **in
	}
	if in.DisableProxyS3 != nil {
		in, out := &in.DisableProxyS3, &out.DisableProxyS3
		*out = new(bool)
		**out = **in
	}
	if in.AWSSecretKeySecretRef != nil {
		in, out := &in.AWSSecretKeySecretRef, &out.AWSSecretKeySecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
}

func (in *S3BlockstoreParameters) DeepCopy() *S3BlockstoreParameters {
	if in == nil {
		return nil
	}
	out := new(S3BlockstoreParameters)
	in.DeepCopyInto(out)
	return out
}

func (in *S3BlockstoreObservation) DeepCopyInto(out *S3BlockstoreObservation) {
	*out = *in
}

func (in *S3BlockstoreObservation) DeepCopy() *S3BlockstoreObservation {
	if in == nil {
		return nil
	}
	out := new(S3BlockstoreObservation)
	in.DeepCopyInto(out)
	return out
}

// ---- S3OplogStore ----

func (in *S3OplogStore) DeepCopyInto(out *S3OplogStore) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *S3OplogStore) DeepCopy() *S3OplogStore {
	if in == nil {
		return nil
	}
	out := new(S3OplogStore)
	in.DeepCopyInto(out)
	return out
}

func (in *S3OplogStore) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *S3OplogStoreList) DeepCopyInto(out *S3OplogStoreList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]S3OplogStore, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *S3OplogStoreList) DeepCopy() *S3OplogStoreList {
	if in == nil {
		return nil
	}
	out := new(S3OplogStoreList)
	in.DeepCopyInto(out)
	return out
}

func (in *S3OplogStoreList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *S3OplogStoreSpec) DeepCopyInto(out *S3OplogStoreSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

func (in *S3OplogStoreSpec) DeepCopy() *S3OplogStoreSpec {
	if in == nil {
		return nil
	}
	out := new(S3OplogStoreSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *S3OplogStoreStatus) DeepCopyInto(out *S3OplogStoreStatus) {
	*out = *in
	in.ConditionedStatus.DeepCopyInto(&out.ConditionedStatus)
	out.AtProvider = in.AtProvider
}

func (in *S3OplogStoreStatus) DeepCopy() *S3OplogStoreStatus {
	if in == nil {
		return nil
	}
	out := new(S3OplogStoreStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *S3OplogStoreParameters) DeepCopyInto(out *S3OplogStoreParameters) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AssignmentEnabled != nil {
		in, out := &in.AssignmentEnabled, &out.AssignmentEnabled
		*out = new(bool)
		**out = **in
	}
	if in.SSL != nil {
		in, out := &in.SSL, &out.SSL
		*out = new(bool)
		**out = **in
	}
	if in.EncryptedCredentials != nil {
		in, out := &in.EncryptedCredentials, &out.EncryptedCredentials
		*out = new(bool)
		**out = **in
	}
	if in.LoadFactor != nil {
		in, out := &in.LoadFactor, &out.LoadFactor
		*out = new(int64)
		**out = **in
	}
	if in.MaxCapacityGB != nil {
		in, out := &in.MaxCapacityGB, &out.MaxCapacityGB
		*out = new(int64)
		**out = **in
	}
	if in.Provisioned != nil {
		in, out := &in.Provisioned, &out.Provisioned
		*out = new(bool)
		**out = **in
	}
	if in.PathStyleAccessEnabled != nil {
		in, out := &in.PathStyleAccessEnabled, &out.PathStyleAccessEnabled
		*out = new(bool)
		**out = **in
	}
	if in.SSEEnabled != nil {
		in, out := &in.SSEEnabled, &out.SSEEnabled
		*out = new(bool)
		**out = **in
	}
	if in.AcceptedTos != nil {
		in, out := &in.AcceptedTos, &out.AcceptedTos
		*out = new(bool)
		**out = **in
	}
	if in.DisableProxyS3 != nil {
		in, out := &in.DisableProxyS3, &out.DisableProxyS3
		*out = new(bool)
		**out = **in
	}
	if in.AWSSecretKeySecretRef != nil {
		in, out := &in.AWSSecretKeySecretRef, &out.AWSSecretKeySecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
}

func (in *S3OplogStoreParameters) DeepCopy() *S3OplogStoreParameters {
	if in == nil {
		return nil
	}
	out := new(S3OplogStoreParameters)
	in.DeepCopyInto(out)
	return out
}

func (in *S3OplogStoreObservation) DeepCopyInto(out *S3OplogStoreObservation) {
	*out = *in
}

func (in *S3OplogStoreObservation) DeepCopy() *S3OplogStoreObservation {
	if in == nil {
		return nil
	}
	out := new(S3OplogStoreObservation)
	in.DeepCopyInto(out)
	return out
}

// ---- BackupDaemon ----

func (in *BackupDaemon) DeepCopyInto(out *BackupDaemon) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *BackupDaemon) DeepCopy() *BackupDaemon {
	if in == nil {
		return nil
	}
	out := new(BackupDaemon)
	in.DeepCopyInto(out)
	return out
}

func (in *BackupDaemon) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *BackupDaemonList) DeepCopyInto(out *BackupDaemonList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BackupDaemon, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *BackupDaemonList) DeepCopy() *BackupDaemonList {
	if in == nil {
		return nil
	}
	out := new(BackupDaemonList)
	in.DeepCopyInto(out)
	return out
}

func (in *BackupDaemonList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *BackupDaemonSpec) DeepCopyInto(out *BackupDaemonSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

func (in *BackupDaemonSpec) DeepCopy() *BackupDaemonSpec {
	if in == nil {
		return nil
	}
	out := new(BackupDaemonSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *BackupDaemonStatus) DeepCopyInto(out *BackupDaemonStatus) {
	*out = *in
	in.ConditionedStatus.DeepCopyInto(&out.ConditionedStatus)
	out.AtProvider = in.AtProvider
}

func (in *BackupDaemonStatus) DeepCopy() *BackupDaemonStatus {
	if in == nil {
		return nil
	}
	out := new(BackupDaemonStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *BackupDaemonParameters) DeepCopyInto(out *BackupDaemonParameters) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AssignmentEnabled != nil {
		in, out := &in.AssignmentEnabled, &out.AssignmentEnabled
		*out = new(bool)
		**out = **in
	}
	if in.SSL != nil {
		in, out := &in.SSL, &out.SSL
		*out = new(bool)
		**out = **in
	}
	if in.EncryptedCredentials != nil {
		in, out := &in.EncryptedCredentials, &out.EncryptedCredentials
		*out = new(bool)
		**out = **in
	}
	if in.BackupJobsEnabled != nil {
		in, out := &in.BackupJobsEnabled, &out.BackupJobsEnabled
		*out = new(bool)
		**out = **in
	}
	if in.GarbageCollectionEnabled != nil {
		in, out := &in.GarbageCollectionEnabled, &out.GarbageCollectionEnabled
		*out = new(bool)
		**out = **in
	}
	if in.ResourceUsageEnabled != nil {
		in, out := &in.ResourceUsageEnabled, &out.ResourceUsageEnabled
		*out = new(bool)
		**out = **in
	}
	if in.RestoreQueryableJobsEnabled != nil {
		in, out := &in.RestoreQueryableJobsEnabled, &out.RestoreQueryableJobsEnabled
		*out = new(bool)
		**out = **in
	}
}

func (in *BackupDaemonParameters) DeepCopy() *BackupDaemonParameters {
	if in == nil {
		return nil
	}
	out := new(BackupDaemonParameters)
	in.DeepCopyInto(out)
	return out
}

func (in *BackupDaemonObservation) DeepCopyInto(out *BackupDaemonObservation) {
	*out = *in
}

func (in *BackupDaemonObservation) DeepCopy() *BackupDaemonObservation {
	if in == nil {
		return nil
	}
	out := new(BackupDaemonObservation)
	in.DeepCopyInto(out)
	return out
}
